### ISSUE TITLE
App Crashes 

### ISSUE THREAD

**Issue by RAIERIN** [Cap-go/capacitor-screen-recorder#3]
The app is crashing in some phone when ScreenRecorder.start() is called for new version of android.  And the error log shows this.

`D/scrcast: createRecorder()
E/SensorManager: registerListenerImpl sensorName:BMI160_ACCELEROMETER Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: io.ionic.starter,callingPid:9852,callingUid:10945
E/MediaRecorder: prepare failed: -2147483648
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 9852
    java.io.IOException: prepare failed.
        at android.media.MediaRecorder._prepare(Native Method)
        at android.media.MediaRecorder.prepare(MediaRecorder.java:1178)
        at dev.bmcreations.scrcast.internal.recorder.service.RecorderService.createRecorder(RecorderService.kt:159)
        at dev.bmcreations.scrcast.internal.recorder.service.RecorderService.access$createRecorder(RecorderService.kt:32)
        at dev.bmcreations.scrcast.internal.recorder.service.RecorderService$recordInternal$1.invokeSuspend(RecorderService.kt:227)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

Android version:
![Screenshot_20220811-140609_Settings](https://user-images.githubusercontent.com/56987934/184158717-d13d94e4-33cb-4b6d-99c7-d42c938dc8f7.jpg)

**Comment by RAIERIN** [comment]
Is there any way i can fix the issue?

**Comment by riderx** [comment]
@RAIERIN for now i don't see a way, the issue is in scrcast.
maybe i could find other plugin with better support

**Comment by riderx** [comment]
maybe i could try to migrate to https://github.com/HBiSoft/HBRecorder

**Comment by RAIERIN** [comment]
@riderx if you could migrate when will you do that.

**Comment by riderx** [comment]
i will check it next week

**Comment by RAIERIN** [comment]
Okay! Thanks

**Comment by kolyneh** [comment]
For this error: E/MediaRecorder: prepare failed: -2147483648
It's BAD_TYPE in native error codes.
Maybe it's because of the outputFormat/videoEncoder/videoFrameRate/videoSize params.
Mostly it's the resolution you set, use a resolution less than 1080P to check if it's working.

**Comment by riderx** [comment]
@kolyneh there no option to set the resolution in `scrcast` where i we could change it ?

**Comment by kolyneh** [comment]
Hi, check this in `scrcast`: 

https://github.com/bmcreations/scrcast/blob/9cc8deea768dedf746c41e35c153db83aeb68b74/library/src/main/java/dev/bmcreations/scrcast/config/Options.kt#L73-L89

It's part of Options.
In DSL like:

```
options{
    video{
         width = 1920
         heigh = 1080
    }
}
```

**Comment by ToriChanIntegration** [comment]
Quick triage refresh on this older crash thread 👋

Given the age of the report and dependency changes since 2022, could someone who still sees this on recent versions share a fresh repro?

Please include:
- plugin version
- Capacitor version
- Android device + OS
- full logcat from `ScreenRecorder.start()` to crash

The historic hint in this thread points to recorder configuration/codec compatibility (`MediaRecorder prepare failed`), so a modern repro would let us decide whether this is still active or safe to close as outdated.

Label suggestion (for maintainers): `bug`, `needs-repro` (and `stale` if no update).
