### ISSUE TITLE
On Android 12 : At the time of start recording app crashes

### ISSUE THREAD

**Issue by navdeep1676** [Cap-go/capacitor-screen-recorder#38]
On Android 12 : At the time of start recording app crashes when we click on start rec button 

Getting Error: InstallClient: Could not copy '/data/local/tmp/.studio/tmp/b3369435/install_server' to '/data/data/com.verse.app/code_cache/install_server-b3369435: out='', err='run-as: unknown package: com.verse.app
run-as: unknown package: com.verse.app
                                                                                                    '
studio.deploy           pid-1993                             E  run-as: unknown package: com.verse.app
studio.deploy           installer                            E  Could not get package user id: run-as: unknown package: com.verse.app
 studio.deploy           installer                            E  Could not find apks for this package: com.verse.app
--------- beginning of crash
3797-3797  AndroidRuntime          pid-3797                           E  FATAL EXCEPTION: main
Process: com.verse.app, PID: 3797
 kotlin.UninitializedPropertyAccessException: lateinit property notificationProvider has not been initialized
 at dev.bmcreations.scrcast.internal.recorder.service.RecorderService.access$getNotificationProvider$p(RecorderService.kt:32)
at dev.bmcreations.scrcast.internal.recorder.service.RecorderService$recordInternal$1.invokeSuspend(RecorderService.kt:208)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7842)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@10558de, Dispatchers.Main]

**Comment by IkerWAT** [comment]
@navdeep1676 I have the same problem. In my case, i am testing it with Android 13 and it crashes. 
Have you been able to solve the problem?

**Comment by riderx** [comment]
Try version 7 i just did and it work properly
